micronaut:
  server:
    cors:
      enabled: true
  application:
    name: feTest
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
